#!/usr/bin/env bash
set -eu # exit on error or unset variable

# Cluster details
REGION=europe-north1-a
CLUSTER=jupyter-se
PROJECT=jupyter-se

# Helm details
NAMESPACE=jhub
RELEASE=jhub
CHART_LOCAL_PATH="."
TIMEOUT=900

# Permission details
gcloud config set compute/region $REGION
gcloud config set container/cluster $CLUSTER
gcloud config set core/project $PROJECT

helm repo add jupyterhub https://jupyterhub.github.io/helm-chart
helm repo add jetstack https://charts.jetstack.io
helm dependency update .
helm upgrade $RELEASE --install $CHART_LOCAL_PATH \
  --force \
  --namespace $NAMESPACE \
  --values secrets/values.yaml \
  --values values.yaml \
  --timeout $TIMEOUT
