dependencies:
  # https://github.com/helm/charts/tree/master/stable/cert-manager
  - name: cert-manager
    version: "v0.7.0"
    repository: "https://charts.jetstack.io"
  
  # https://github.com/helm/charts/tree/master/stable/nginx-ingress
  - name: nginx-ingress
    version: "1.4.0"
    repository: "https://kubernetes-charts.storage.googleapis.com"

  # https://github.com/jupyterhub/zero-to-jupyterhub-k8s
  # https://jupyterhub.github.io/helm-chart/
  - name: jupyterhub
    version: "0.9-61cf357"
    repository: "https://jupyterhub.github.io/helm-chart"
