---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: jupyter-se
  labels:
    helm.sh/chart: {{ include "jupyter-se.chart" . }}
    app.kubernetes.io/name: {{ include "jupyter-se.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # production: https://acme-v02.api.letsencrypt.org/directory
    # staging:    https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.letsencrypt.contactEmail }}
    privateKeySecretRef:
      name: jupyter-se-acme-key
    http01: {}
